<?php

/**
 * Konfiguracja bazy danych.
 *
 * Reszta konfiguracji znajduje się w bazie danych.
 */

return array(

'ogolne' => array
(
	'modul_brak_uprawnien_do_akcji' => 'Brak uprawnień do wykonania akcji',
	'system_brak_udostepnianej_lokalizacji' => 'UWAGA!!! Aplikacja wymaga abyś udostepnił swoją lokalizację. Zmień ustawienia swojej przeglądarki tak aby udostępniała lokalizację dla witryny app.bktas.no',
),

'uslugi' => array(
	'Admin' => 'Panel administracyjny',
	'Ajax' => 'Żądania AJAX',
	'Http' => 'Strona WWW',
	'Download' => 'Pliki prywatne',
	'Rss' => 'Kanały RSS',
	'Cron' => 'Zadania cykliczne',
	'Popup' => 'Wyświetlanie w oknie',
	'Bloki' => 'Bloki z treścią', // to nie jest usluga ale jest uzywane w uprawnieniach
	'System' => 'Ustawienia CMS-a', // to nie jest usluga ale jest uzywane w konfiguracji
),

'blokady' => array
(
	'tryb_serwisowy' => 'Tryb serwisowy.',
	'trwaja_prace_serwisowe' => 'Przepraszamy trwają prace serwisowe.',
),

'bledy' => array
(
	'blad_zadania' => 'Błąd żądania Http.',
	'nie_znaleziono_projektu' => 'Nie znaleziono serwisu do którego się odwołujesz. Spróbuj ponownie wpisać poprawny adres lub skontaktuj się z administratorem.',
	'nie_znaleziono_stony' => 'Nie znaleziono strony o podanym adresie url. Spróbuj ponownie wpisać poprawny adres lub skontaktuj się z administratorem.',
	'nie_znaleziono_pliku' => 'Nie znaleziono pliku o podanym adresie url. Spróbuj ponownie wpisać poprawny adres lub skontaktuj się z administratorem.',
	'nie_zalogowany_uzytkownik' => 'Nie jesteś zalogowanym użytkownikiem. Zaloguj się aby wykonać żądaną operację.',
	'brak_uprawnien_do_zasobu' => 'Nie masz uprawnień do zasobu. Skontaktuj się z administratorem.',

	'blad_aplikacji' => 'Błąd wewnętrzny aplikacji.',
	'przerwane_przetwarzanie_strony' => 'Wystąpił błąd podczas przetwarzania strony. Spróbuj odświeżyć stronę w przeglądarce lub skontaktuj się z administratorem.',
),

'tabela_danych' => array
(
	'etykieta_dodaj' => 'Add',
	'etykieta_edytuj' => 'Edit',
	'etykieta_podglad' => 'Preview',
	'etykieta_publikuj' => 'Publish',
	'etykieta_usun' => 'Delete',
	'etykieta_potwierdz_usun' => 'Do you wannt to delete selected row?',
	'etykieta_zaznacz_wszystkie' => 'Check all',
	'etykieta_odznacz_wszystkie' => 'Uncheck all',
	'blad_zaznaczenie_puste' => 'No rows selected!',
	'etykieta_odwroc_zaznaczenie' => 'Inverse selection',
	'etykieta_eksportuj_zaznaczone' => 'Export selected',
	'etykieta_usun_zaznaczone' => 'Delete selected',
	'etykieta_potwierdz_usun_zaznaczone' => 'Do you want to delete all selected rows?',
	'etykieta_brak_wierszy' => 'No data to display at this time',
	'etykieta_sortuj_po' => 'Order by: ',
),

'tabela_sortowanie' => array
(
	'wlacz_sortowanie' => 'Włącz sortowanie',
	'wylacz_sortowanie' => 'Wyłącz sortowanie',
	'zapisz_sortowanie' => 'Zapisz sortowanie',
),

'walidatory' => array
(
	'walidator_adres_ip_nieprawidlowy_adres' => 'IP address is invalid.',
	'walidator_data_iso_nieprawidlowa_data' => 'Date is invalid.',
	'walidator_data_czas_iso_nieprawidlowa_data' => 'Date is invalid.',
	'walidator_godzina_nieprawidlowa_godzina' => 'Time is invalid',
	'walidator_data_pl_nieprawidlowa_data' => 'Date is invalid.',
	'walidator_email_nieprawidlowy_email' => 'E-mail address is invalid.',
	'walidator_email_serwer_nie_obsluguje_poczty' => 'E-mail address is invalid.',
	'walidator_kod_pocztowy_nieprawidlowy_kod' => 'Postcode is invalid.',
	'walidator_kwota_nieprawidlowa_kwota' => 'Amount is invalid.',
	'walidator_liczba_calkowita_nieprawidlowa_liczba' => 'This value is not integer.',
	'walidator_liczba_zmiennoprzecinkowa_nieprawidlowa_liczba' => 'This value is not float.',
	'walidator_mniejsze_od_liczba_za_duza' => 'Number is too big.',
	'walidator_nie_puste_wartosc_pusta' => 'The value cannot remain empty.',
	'walidator_nip_nieprawidlowy_nip' => 'Ivalid tax number.',
	'walidator_nr_konta_iban_nieprawidlowy_numer' => 'Invalid IBAN number.',
	'walidator_nr_konta_nrb_nieprawidlowy_numer' => 'Invalid account number.',
	'walidator_numer_dowodu_nieprawidlowy_numer' => 'Document number invalid',
	'walidator_numer_paszportu_nieprawidlowy_numer' => 'Document number invalid',
	'walidator_pesel_nieprawidlowy_numer' => 'Personal number invalid',
	'walidator_pesel_data_urodzenia_nie_zgadza_sie' => 'Date of birth is not accurate with personal number',
	'walidator_poprawny_upload_UPLOAD_ERR_OK' => 'Upload successfull.',
	'walidator_poprawny_upload_UPLOAD_ERR_INI_SIZE' => 'File size was exceeded.',
	'walidator_poprawny_upload_UPLOAD_ERR_FORM_SIZE' => 'File size was exceeded.',
	'walidator_poprawny_upload_UPLOAD_ERR_PARTIAL' => 'File uploaded partially.',
	'walidator_poprawny_upload_UPLOAD_ERR_NO_FILE' => 'File was not uploaded.',
	'walidator_poprawny_upload_UPLOAD_ERR_NO_TMP_DIR' => 'No temp dir.',
	'walidator_poprawny_upload_UPLOAD_ERR_CANT_WRITE' => 'Cannot write file on server disk.',
	'walidator_poprawny_upload_UPLOAD_ERR_EXTENSION' => 'File extension invalid.',
	'walidator_puste_nie_puste' => 'Value not empty',
	'walidator_rowne_nie_jest_rowne' => 'Invalid value.',
	'walidator_rozne_od_nie_jest_rozne' => 'Invalid value.',
	'walidator_rozszerzenie_pliku_nieprawidlowe' => 'File extension is invalid.',
	'walidator_telefon_nieprawidlowy_numer' => 'Telephone number invalid.',
	'walidator_url_nieprawidlowy_url' => 'URL address is invalid',
	'walidator_url_serwer_nie_odpowiada' => 'Server does not respond',
	'walidator_wieksze_od_liczba_za_mala' => 'value too low.',
	'walidator_wyrazenie_regularne_niespelnione' => 'Invalid value',
	'walidator_niedozwolone_wartosci_niedozwolona_wartosc' => 'Invalid value.',
	'walidator_dozwolone_wartosci_niedozwolona_wartosc' => 'Value not acceptable.',
	'walidator_zawiera_tekst_brak_tekstu' => 'Required text not found',
	'walidator_domena_nieprawidlowa_domena' => 'Domain invalid',
	'walidator_domena_serwer_nie_odpowiada' => 'Server does not respond',
	'walidator_krotsze_od_wartosc_za_dluga' => 'Value too long',
	'walidator_dluzsze_od_wartosc_za_krotka' => 'Value too short',
),

'inputy' => array
(
	'input_autocomplite_lista_etykieta_dostepne' => 'Dostępne',
	'input_autocomplite_lista_etykieta_wyszukaj' => 'Search',
	'input_autocomplite_lista_etykieta_wybrane' => 'Selected',
	'input_autocomplite_lista_etykieta_dodaj_inne' => 'Dodaj inne',
	'input_autocomplite_lista_etykieta_dodaj_inne_potwierdz' => 'Dodaj',
	'input_autocomplite_lista_etykieta_dodaj' => ' << ',
	'input_autocomplite_lista_etykieta_usun' => ' >> ',

	'input_captcha_text_etykieta_pytanie' => 'Podaj wynik operacji: ',
	'input_captcha_text_etykieta_1' => 'jeden',
	'input_captcha_text_etykieta_2' => 'dwa',
	'input_captcha_text_etykieta_3' => 'trzy',
	'input_captcha_text_etykieta_4' => 'cztery',
	'input_captcha_text_etykieta_5' => 'pięć',
	'input_captcha_text_etykieta_6' => 'sześć',
	'input_captcha_text_etykieta_7' => 'siedem',
	'input_captcha_text_etykieta_8' => 'osiem',
	'input_captcha_text_etykieta_9' => 'dziewięć',
	'input_captcha_text_etykieta_10' => 'dziesięć',
	'input_captcha_text_etykieta_11' => 'jedenaście',
	'input_captcha_text_etykieta_12' => 'dwanaście',
	'input_captcha_text_etykieta_13' => 'trzynaście',
	'input_captcha_text_etykieta_14' => 'czternaście',
	'input_captcha_text_etykieta_15' => 'piętnaście',
	'input_captcha_text_etykieta_16' => 'szesnaście',
	'input_captcha_text_etykieta_17' => 'siedemnaście',
	'input_captcha_text_etykieta_18' => 'osiemnaście',
	'input_captcha_text_etykieta_19' => 'dziewiętnaście',
	'input_captcha_text_etykieta_20' => 'dwadzieścia',
	'input_captcha_text_etykieta_plus' => 'plus',
	'input_captcha_text_etykieta_minus' => 'minus',
	'input_captcha_text_etykieta_razy' => 'razy',

	'input_cena_nieprawidlowa_cena' => 'Podana cena nie jest poprawna.',

	'input_data_miesiace' => array('Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'),
	'input_data_miesiace_skrocone' => array('Sty', 'Lut', 'Mar', 'Kwie', 'Maj', 'Czer', 'Lip', 'Sie', 'Wrze', 'Paź', 'Lis', 'Gru'),
	'input_data_dni' => array('Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'),
	'input_data_dni_skrocone' => array('Ni', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'),
	'input_data_dni_minimum' => array('N', 'Pn', 'W', 'Ś', 'C', 'Pt', 'S'),

	'input_lista_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_lista_etykieta_usun_pole' => 'Usuń ostatnie pole',
	'input_lista_etykieta_usun_pole_wybrane' => 'Usuń',

	'input_mapa_google_etykieta_x' => 'X: ',
	'input_mapa_google_etykieta_y' => 'Y: ',
	'input_mapa_google_etykieta_uzyj_mapy' => 'Użyj mapy',
	'input_mapa_google_etykieta_ukryj_mape' => 'Ukryj mapę',

	'input_miniatury_etykieta_kod' => 'Kod ',
	'input_miniatury_etykieta_wysokosc' => ' Wys.: ',
	'input_miniatury_etykieta_szerokosc' => ' Szer.: ',
	'input_miniatury_etykieta_metoda' => ' Akcja ',

	'input_miniatury_metoda_scale' => 'Skaluj caly obraz',
	'input_miniatury_metoda_crop' => 'Skaluj i utnij nadmiar',
	'input_miniatury_metoda_scaleCrop' => 'Skaluj i utnij nadmiar jeśli potrzeba',
	'input_miniatury_metoda_resize' => 'Rozciągnij do wymiarów',

	'input_miniatury_etykieta_dodaj_pole' => 'Dodaj miniaturę',
	'input_miniatury_etykieta_usun_pole' => 'Usuń ostatnią',

	'input_tablica_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_tablica_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_tablica_etykieta_usun_pole' => 'Usuń ostatnie pole',

	'input_multi_text_select_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_multi_text_select_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_multi_text_select_etykieta_usun_pole' => 'Usuń ostatnie pole',
	
	'input_atrybuty_etykieta_dodaj_pole' => 'Add next attribute',
	'input_atrybuty_etykieta_usun_pole' => 'Delete last atribute',
	'input_atrybuty_etykieta_podzial_uprawnienia' => ' &rArr; ',
	'input_atrybuty_etykieta_podzial' => ' &rArr; ',

	'input_multi_upload_etykieta_przesylanie' => 'Przesyłanie...',
	'input_multi_upload_blad_kolejka_za_dluga' => 'Błąd! Zbyt wiele plików oczekuje na przesłanie.',
	'input_multi_upload_etykieta_tworzenie_miniaturek' => 'Tworzenie miniaturek...',
	'input_multi_upload_etykieta_miniaturki_stworzone' => 'Miniaturki gotowe.',
	'input_multi_upload_etykieta_koniec_ladowania' => 'Wszystkie zdjęcia zostały przesłane.',

	'input_multi_upload_plikow_blad_uploadu' => 'Wystąpił błąd podczas wysyałania pliku: {file} na serwer.',
	'input_multi_upload_plikow_blad_zle_rozszerzenie' => '{file} ma złe rozszerzenie. Tylko rozszerzenia {extensions} są dozwolone.',
	'input_multi_upload_plikow_blad_za_duzy_plik' => '{file} jest za duży. Maksymalna wielkość pliku to {sizeLimit}.',
	'input_multi_upload_plikow_blad_za_maly_plik' => '{file} jest za mały. Minimalna wielkość pliku to {minSizeLimit}.',
	'input_multi_upload_plikow_blad_pusty_plik' => '{file} jest pusty, proszę wysłać prawidłwy plik.',
	'input_multi_upload_plikow_za_duzo_plikow' => 'Przekroczono limit plików do wysłania. Wysłana liczba plików: <strong>{numSendFiles}</strong>. Można wysłać maksymalnie <strong>{numFilesLeft}</strong>.',
	'input_multi_upload_plikow_etykieta_trwa_wysylanie' => 'Pliki aktualnie są wysyłane, opuszczenie strony jest związane z anulowaniem wysyłania.',
	'input_multi_upload_plikow_etykieta_wybierz_pliki' => 'Wybierz pliki',
	'input_multi_upload_plikow_etykieta_dozwolone_pliki' => 'Dozwolone typy plików: {DOZWOLONE_ROZSZERZNIA}.',
	'input_multi_upload_plikow_etykieta_max_rozmiar_pliku' => 'Max. rozmiar pliku to {MAX_ROZMIAR} MB.',
	'input_multi_upload_plikow_etykieta_opis' => 'Opis:',
	'input_multi_upload_plikow_etykieta_zaznacz_wszystkie' => 'Check / Uncheck',
	'input_multi_upload_plikow_etykieta_usun_zaznaczone' => 'Delete checked',
	'input_multi_upload_plikow_etykieta_czy_usunac_pliki' => 'Czy na pewno usunąć zaznaczone pliki?',
	'input_multi_upload_plikow_etykieta_czy_usunac_plik' => 'Czy na pewno usunąć plik?',
	'input_multi_upload_plikow_etykieta_usun' => 'Delete this file',
	'input_multi_upload_plikow_etykieta_usunieto' => 'Plik został usunięty.',
	'input_multi_upload_plikow_etykieta_blokada_tytul' => 'Ostrzeżenie',
	'input_multi_upload_plikow_etykieta_blokada_tresc' => 'Trwa przesyłanie plików. Zaczekaj na zakończenie.',

	'input_multi_upload_zdjec_blad_uploadu' => 'Wystąpił błąd podczas wysyałania pliku: {file} na serwer.',
	'input_multi_upload_zdjec_blad_zle_rozszerzenie' => '{file} ma złe rozszerzenie. Tylko rozszerzenia {extensions} są dozwolone.',
	'input_multi_upload_zdjec_blad_za_duzy_plik' => '{file} jest za duży. Maksymalna wielkość pliku to {sizeLimit}.',
	'input_multi_upload_zdjec_blad_za_maly_plik' => '{file} jest za mały. Minimalna wielkość pliku to {minSizeLimit}.',
	'input_multi_upload_zdjec_blad_pusty_plik' => '{file} jest pusty, proszę wysłać prawidłwy plik.',
	'input_multi_upload_zdjec_za_duzo_plikow' => 'Przekroczono limit zdjęć do wysłania. Wysłana liczba zdjęć: <strong>{numSendFiles}</strong>. Można wysłać maksymalnie <strong>{numFilesLeft}</strong>.',
	'input_multi_upload_zdjec_etykieta_trwa_wysylanie' => 'Pliki aktualnie są wysyłane, opuszczenie strony jest związane z anulowaniem wysyłania.',
	'input_multi_upload_zdjec_etykieta_wybierz_pliki' => 'Wybierz pliki',
	'input_multi_upload_zdjec_etykieta_dozwolone_pliki' => 'Dozwolone typy plików: {DOZWOLONE_ROZSZERZNIA}.',
	'input_multi_upload_zdjec_etykieta_max_rozmiar_pliku' => 'Max. rozmiar pliku to {MAX_ROZMIAR} MB.',
	'input_multi_upload_zdjec_etykieta_opis' => 'Opis:',
	'input_multi_upload_zdjec_etykieta_zaznacz_wszystkie' => 'Zaznacz / Odznacz',
	'input_multi_upload_zdjec_etykieta_usun_zaznaczone' => 'Usuń zaznaczone',
	'input_multi_upload_zdjec_etykieta_czy_usunac_pliki' => 'Czy na pewno usunąć zaznaczone zdjęcia?',
	'input_multi_upload_zdjec_etykieta_czy_usunac_plik' => 'Czy na pewno usunąć zdjęcie?',
	'input_multi_upload_zdjec_etykieta_usun' => 'Usuń to zdjęcie',
	'input_multi_upload_zdjec_etykieta_croper' => 'Popraw',
	'input_multi_upload_zdjec_etykieta_usunieto' => 'Zdjecie zostało usunięte.',
	'input_multi_upload_zdjec_etykieta_blad' => 'Wystąpił błąd.',
	'input_multi_upload_zdjec_etykieta_blokada_tytul' => 'Ostrzeżenie',
	'input_multi_upload_zdjec_etykieta_blokada_tresc' => 'Trwa przesyłanie plików. Zaczekaj na zakończenie.',

	'input_pager_etykieta_zakres' => 'Ilość linków obok wybranej strony',
	'input_pager_etykieta_dostepneZakresy' => 'Opcje ilości wyników na stronie',
	'input_pager_etykieta_wyborStrony' => 'Sposób wybierania strony',
	'input_pager_etykieta_wyborZakresu' => 'Sposób wybierania ilości na stronie',
	'input_pager_etykieta_skoczDo' => 'Pole do wprowadzenia numeru strony',
	'input_pager_etykieta_pierwszaOstatnia' => 'Linki do pierwszej i ostatniej strony',
	'input_pager_etykieta_poprzedniaNastepna' => 'Linki do poprzedniej i następnej strony',
	'input_pager_etykieta_skoki' => 'Linki do odległych stron w postaci:<br/>"liczba_stron"=>"etykieta"(opcjonalnie)<br>np."15"=>"Skocz o 15"',
	'input_pager_etykieta_skoki_dodaj' => 'Dodaj',
	'input_pager_etykieta_skoki_usun' => 'Usuń',
	'input_pager_etykieta_podzial' => '=>',
	'input_pager_wybor_brak' => 'Nie pokazuj',
	'input_pager_wybor_linki' => 'Linki',
	'input_pager_wybor_select' => 'Lista wyboru',
	
	'input_select_rabat_etykieta_waluta' => 'kr',
	'input_select_rabat_etykieta_rodzaj' => 'Type of discount: ',
	'input_select_rabat_etykieta_rabat_rodzaj_procentowy' => 'Percent',
	'input_select_rabat_etykieta_rabat_rodzaj_kwotowy' => 'Amount',
	'input_select_rabat_etykieta_rabat_na_calosc' => 'Discount for the whole position',
	'input_select_rabat_etykieta_procent' => '%',
	'input_select_rabat_etykieta_discount' => 'Discount: ',
	'input_select_rabat_etykieta_total' => 'Total: ',
	'input_select_rabat_etykieta_total_sum' => 'Total after discount : ',

	'input_plik_etykieta_usun' => 'Usuń',
	'input_plik_etykieta_opis' => 'Opis: ',

	'input_podglad_miniaturek_etykieta_tytul' => 'Tytuł',
	'input_podglad_miniaturek_etykieta_opis' => 'Opis',
	'input_podglad_miniaturek_etykieta_autor' => 'Autor',
	'input_podglad_miniaturek_etykieta_zdjecie_glowne' => 'zd. główne',

	'input_select_cron_etykieta_minuty' => 'Minuty',
	'input_select_cron_etykieta_godziny' => 'Godziny',
	'input_select_cron_etykieta_dni' => 'Dni',
	'input_select_cron_etykieta_miesiace' => 'Miesiace',
	'input_select_cron_etykieta_dni_tygodnia' => 'Dni tyg.(0 - Niedziela)',


	'input_selectdrzewo2_captcha_text_etykieta_podpowiedz' => 'Wpisz słowo, następnie kliknij by wybrać scieżkę i szczegółową pozycję: ',


	'input_selectdrzewo3_input_captcha_text_etykieta_podpowiedz' => '',
	'input_selectdrzewo3_button.szukaj' => 'Znajdź kategorię',
	'input_selectdrzewo3_wybierz.lub' => 'lub',
	'input_selectdrzewo3_wybierz.recznie' => 'wybierz kategorię ręcznie',
	'input_selectdrzewo3_wyszukaj_kategorie' => 'Wybierz kategorię, która najabrdziej pasuje do Twojego produktu:',
	'input_selectdrzewo3_wyszukaj_kategorie_brak' => 'Nie znaleźliśmy kategorii odpowiedniej dla Twojego przedmiotu.',
	'input_selectdrzewo3_wyszukaj_kategorie_brak2' => 'Popraw jego nazwę lub ',
	//'domyslny_napis' => 'Wpisz nazwę przedmiotu...',

	'input_select_wiele_wartosc_juz_wybrana' => 'Ta wartość już została wybrana wcześniej. Jedna z wartości zostanie zmieniona',

	'input_select_produkty_projekt_etykieta_kategoria' => 'Category: ',
	'input_select_produkty_projekt_etykieta_procent' => '%',
	'input_select_produkty_projekt_etykieta_waluta' => 'kr ',
	'input_select_produkty_projekt_etykieta_ilosc' => 'Qty: ',
	'input_select_produkty_projekt_etykieta_kwota' => 'Price: ',
	'input_select_produkty_projekt_etykieta_kwota_total' => 'Total: ',
	'input_select_produkty_projekt_etykieta_kwota_znaczek' => ',-',
	'input_select_produkty_projekt_etykieta_vat' => 'Tax: ',
	
	'input_select_kreditnota_etykieta_waluta' => 'kr ',
	'input_select_kreditnota_etykieta_procent' => '% ',
	'input_select_kreditnota_etykieta_minus' => ' - ',
	'input_select_kreditnota_etykieta_ilosc' => 'qty.',
	'input_select_kreditnota_etykieta_mnoznik' => '*',
	'input_select_etykieta_zmniesz_kwote' => 'Reduce the amount / quantity',
	
	'input_tablica_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_tablica_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_tablica_etykieta_usun_pole' => 'Usuń ostatnie pole',
	'input_tablica_etykieta_usun_pole_wybrane' => 'Usuń',

	'input_tablica_select_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_tablica_select_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_tablica_select_etykieta_usun_pole' => 'Usuń ostatnie pole',
	'input_tablica_select_etykieta_usun_pole_wybrane' => 'Usuń',

	'input_tablica_specjalna_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_tablica_specjalna_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_tablica_specjalna_etykieta_usun_pole' => 'Usuń ostatnie pole',
	'input_tablica_specjalna_etykieta_usun_pole_wybrane' => 'Usuń',

	'input_tablica_zaawansowana_etykieta_podzial' => '&nbsp;->&nbsp;',
	'input_tablica_zaawansowana_etykieta_dodaj_pole' => 'Dodaj kolejne pole',
	'input_tablica_zaawansowana_etykieta_usun_pole' => 'Usuń ostatnie pole',
	'input_tablica_zaawansowana_etykieta_usun_pole_wybrane' => 'Usuń',

	'input_text_etykieta_licznik' => 'Liczba znaków: {LICZBA} z {LIMIT} znaków',
	'input_text_etykieta_licznik_bez_spacji' => 'Liczba znaków: {LICZBA} z {LIMIT} znaków (bez spacji) ',
	
	'input_podpis_naglowek' => 'Leave your signature here : ',
	'input_podpis_zablokujScroll' => 'Disable scroll page',
	'input_podpis_odblokujScroll' => 'Enable scroll page',

	'input_textarea_etykieta_wlacz_wylacz' => 'Włącz/wyłącz edytor',

	'input_zaawansowana_mapa_googla_etykieta_x' => 'X: ',
	'input_zaawansowana_mapa_googla_etykieta_y' => 'Y: ',
	'input_zaawansowana_mapa_googla_etykieta_uzyj_mapy' => 'Użyj mapy',
	'input_zaawansowana_mapa_googla_etykieta_ukryj_mape' => 'Ukryj mapę',
	'input_zaawansowana_mapa_googla_etykieta_geolokalizacja' => 'Szukaj',
	'input_zaawansowana_mapa_googla_problem' => 'Nie znaleziono adresu, powód: ',
	'input_zaawansowana_mapa_googla_tytul' => 'Adres siedziby:',
	'input_zaawansowana_mapa_googla_kody_bledow' => array(
		'ZERO_RESULTS' => 'brak wyników',
		'OVER_QUERY_LIMIT' => 'przekroczono limit zapytań',
		'REQUEST_DENIED' => 'żądanie odrzucone',
		'INVALID_REQUEST' => 'brak podanego adresu w bazie bądź adres jest nieprawidłowy',
	),

	'input_zdjecie_etykieta_usun' => 'Usuń to zdjęcie',
	'input_zdjecie_etykieta_usun_tytul' => 'Usuwanie obrazu',
	'input_zdjecie_etykieta_usun_pytanie' => 'Czy na pewno usunąć obraz?',
	'input_zdjecie_etykieta_popraw' => 'Popraw miniaturke',
	'input_zdjecie_etykieta_wybierz' => 'Wybierz miniaturke: ',
	'input_zdjecie_etykieta_zatwierdz' => 'Zatwierdź',
	'input_zdjecie_etykieta_opis' => 'Opis: ',
	'input_zdjecie_etykieta_dozwolone_typy' => 'Dozwolone typy plików: ',

	'input_zdjecie_cropowane_etykieta_usun' => 'Usuń to zdjęcie',
	'input_zdjecie_cropowane_etykieta_usun_tytul' => 'Usuwanie obrazu',
	'input_zdjecie_cropowane_etykieta_usun_pytanie' => 'Czy na pewno usunąć obraz?',
	'input_zdjecie_cropowane_etykieta_popraw' => 'Popraw miniaturke',
	'input_zdjecie_cropowane_etykieta_wybierz' => 'Wybierz miniaturke: ',
	'input_zdjecie_cropowane_etykieta_zatwierdz' => 'Zatwierdź',
	'input_zdjecie_cropowane_etykieta_opis' => 'Opis: ',
	'input_zdjecie_cropowane_etykieta_dozwolone_typy' => 'Dozwolone typy plików: ',
	'input_zdjecie_cropowane_etykieta_blad' => 'Wystąpił błąd.',
	
	'select_klienci_etykieta_dodaj' => 'Dodaj nowego klienta',
	'select_klienci_etykieta_edytuj' => 'Edytuj klienta',
	'select_klienci_etykieta_zamien' => 'Wybierz innego klienta',
	'select_klienci_etykieta_powrot_podglad' => 'Powrót',
	
	'input_szukaj_produkty_magazyn_etykieta' => 'Search product',
	'select_produkty_komunikat_opuszczenie_strony' => 'Czy na pewno chcesz opuścić tą stronę? - Wszystkie dokonane do tej pory zmiany nie zostaną zapisane!',
	'select_produkty_potwierdz_resetuj' => 'Czy jesteś pewien że chcesz usunąc podstawowy produkt? To oznacza rozpoczęcie dodawania produktów od początku.',
),

'formularz' => array(
	'etykieta_region_zwin_rozwin' => 'zwiń / rozwiń',
),

'pagery' => array
(
	'pager_wstecz' => '&laquo;',
	'pager_przod' => '&raquo;',
	'pager_pierwsza' => 'Pierwsza strona',
	'pager_ostatnia' => 'Ostatnia strona',
	'pager_poprzednia' => 'Poprzednia strona',
	'pager_nastepna' => 'Następna strona',
	'pager_wybierz_strone' => 'Wybierz stronę: ',
	'pager_wybierz_przedzial' => 'Przedział: ',
	'pager_wybierz_zakres' => '&nbsp;Na stronie:&nbsp;',
	'pager_pokaz_wszystko' => 'Wszystko',
	'pager_na_stronie' => '&nbsp;Na stronie:&nbsp;',
	'pager_ilosc' => 'Wyników: ',
	'pager_skocz_do' => 'Skocz do strony: ',
	'pager_skocz' => 'Skod do',
	'pager_wartosc_skocz_do' => '#'
),

'sortery' => array(
	'etykieta_sorter' => 'Sortuj wg:',
	'etykieta_asc' => '%s, rosnąco',
	'etykieta_desc' => '%s, malejąco',
),

'kraje' => array (
	'pl' => 'Polska',
	'af' => 'Afganistan',
	'al' => 'Albania',
	'dz' => 'Algieria',
	'ad' => 'Andora',
	'en' => 'Anglia',
	'ao' => 'Angola',
	'ai' => 'Anguilla',
	'aq' => 'Antarktyda',
	'ag' => 'Antigua i Barbuda',
	'an' => 'Antyle Holenderskie',
	'sa' => 'Arabia Saudyjska',
	'ar' => 'Argentyna',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbejdżan',
	'bs' => 'Bahamy',
	'bh' => 'Bahrajn',
	'bd' => 'Bangladesz',
	'bb' => 'Barbados',
	'be' => 'Belgia',
	'bz' => 'Belize',
	'bj' => 'Benin',
	'bm' => 'Bermudy',
	'bt' => 'Bhutan',
	'by' => 'Białoruś',
	'mm' => 'Birma (Myanmar)',
	'bo' => 'Boliwia',
	'bw' => 'Botswana',
	'ba' => 'Bośnia i Hercegowina',
	'br' => 'Brazylia',
	'bn' => 'Brunei',
	'io' => 'Brytyjskie Terytorium Oceanu Indyjskiego',
	'vg' => 'Brytyjskie Wyspy Dziewicze',
	'bf' => 'Burkina Faso',
	'bi' => 'Burundi',
	'bg' => 'Bułgaria',
	'cl' => 'Chile',
	'cn' => 'Chiny',
	'hr' => 'Chorwacja',
	'cy' => 'Cypr',
	'td' => 'Czad',
	'me' => 'Czarnogóra',
	'um' => 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
	'dk' => 'Dania',
	'cd' => 'Demokratyczna Republika Konga',
	'dm' => 'Dominika',
	'dj' => 'Dżibuti',
	'eg' => 'Egipt',
	'ec' => 'Ekwador',
	'er' => 'Erytrea',
	'ee' => 'Estonia',
	'et' => 'Etiopia',
	'fk' => 'Falklandy (Malwiny)',
	'fj' => 'Fidżi',
	'ph' => 'Filipiny',
	'fi' => 'Finlandia',
	'fr' => 'Francja',
	'tf' => 'Francuskie Terytoria Południowe',
	'ga' => 'Gabon',
	'gm' => 'Gambia',
	'gs' => 'Georgia Południowa i Sandwich Południowy',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gr' => 'Grecja',
	'gd' => 'Grenada',
	'gl' => 'Grenlandia',
	'ge' => 'Gruzja',
	'gu' => 'Guam',
	'gg' => 'Guernsey',
	'gy' => 'Gujana',
	'gf' => 'Gujana Francuska',
	'gp' => 'Gwadelupa',
	'gt' => 'Gwatemala',
	'gn' => 'Gwinea',
	'gw' => 'Gwinea Bissau',
	'gq' => 'Gwinea Równikowa',
	'ht' => 'Haiti',
	'es' => 'Hiszpania',
	'nl' => 'Holandia (Niderlandy)',
	'hn' => 'Honduras',
	'hk' => 'Hongkong',
	'in' => 'Indie',
	'id' => 'Indonezja',
	'iq' => 'Irak',
	'ir' => 'Iran',
	'ie' => 'Irlandia',
	'is' => 'Islandia',
	'il' => 'Izrael',
	'jm' => 'Jamajka',
	'sj' => 'Jan Mayen',
	'jp' => 'Japonia',
	'ye' => 'Jemen',
	'je' => 'Jersey',
	'jo' => 'Jordania',
	'ky' => 'Kajmany',
	'kh' => 'Kambodża',
	'cm' => 'Kamerun',
	'ca' => 'Kanada',
	'qa' => 'Katar',
	'kz' => 'Kazachstan',
	'ke' => 'Kenia',
	'kg' => 'Kirgistan',
	'ki' => 'Kiribati',
	'co' => 'Kolumbia',
	'km' => 'Komory',
	'cg' => 'Kongo',
	'kr' => 'Korea Południowa',
	'kp' => 'Korea Północna',
	'cr' => 'Kostaryka',
	'cu' => 'Kuba',
	'kw' => 'Kuwejt',
	'la' => 'Laos',
	'ls' => 'Lesotho',
	'lb' => 'Liban',
	'lr' => 'Liberia',
	'ly' => 'Libia',
	'li' => 'Liechtenstein',
	'lt' => 'Litwa',
	'lu' => 'Luksemburg',
	'lv' => 'Łotwa',
	'mk' => 'Macedonia',
	'mg' => 'Madagaskar',
	'yt' => 'Majotta',
	'mo' => 'Makau',
	'mw' => 'Malawi',
	'mv' => 'Malediwy',
	'my' => 'Malezja',
	'ml' => 'Mali',
	'mt' => 'Malta',
	'mp' => 'Mariany Północne',
	'ma' => 'Maroko',
	'mq' => 'Martynika',
	'mr' => 'Mauretania',
	'mu' => 'Mauritius',
	'mx' => 'Meksyk',
	'fm' => 'Mikronezja',
	'mc' => 'Monako',
	'mn' => 'Mongolia',
	'ms' => 'Montserrat',
	'mz' => 'Mozambik',
	'md' => 'Mołdawia',
	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'de' => 'Niemcy',
	'ne' => 'Niger',
	'ng' => 'Nigeria',
	'ni' => 'Nikaragua Nikaragua',
	'nu' => 'Niue',
	'nf' => 'Norfolk',
	'no' => 'Norwegia',
	'nc' => 'Nowa Kaledonia',
	'nz' => 'Nowa Zelandia',
	'om' => 'Oman',
	'pk' => 'Pakistan',
	'pw' => 'Palau',
	'ps' => 'Palestyna',
	'pa' => 'Panama',
	'pg' => 'Papua-Nowa Gwinea',
	'py' => 'Paragwaj',
	'pe' => 'Peru',
	'pn' => 'Pitcairn',
	'pf' => 'Polinezja Francuska',
	'pr' => 'Portoryko',
	'pt' => 'Portugalia',
	'cz' => 'Republika Czeska',
	'do' => 'Republika Dominikańska',
	'za' => 'Republika Południowej Afryki',
	'cv' => 'Republika Zielonego Przylądka',
	'cf' => 'Republika Środkowoafrykańska',
	're' => 'Reunion',
	'ru' => 'Rosja',
	'ro' => 'Rumunia',
	'rw' => 'Rwanda',
	'eh' => 'Sahara Zachodnia',
	'kn' => 'Saint Kitts i Nevis',
	'lc' => 'Saint Lucia',
	'vc' => 'Saint Vincent i Grenadyny',
	'bl' => 'Saint-Barthélemy',
	'mf' => 'Saint-Martin',
	'pm' => 'Saint-Pierre i Miquelon',
	'sv' => 'Salwador',
	'ws' => 'Samoa',
	'as' => 'Samoa Amerykańskie',
	'sm' => 'San Marino',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seszele',
	'sl' => 'Sierra Leone',
	'sg' => 'Singapur',
	'so' => 'Somalia',
	'lk' => 'Sri Lanka',
	'us' => 'Stany Zjednoczone',
	'sz' => 'Suazi',
	'sd' => 'Sudan',
	'sr' => 'Surinam',
	'sy' => 'Syria',
	'ch' => 'Szwajcaria',
	'se' => 'Szwecja',
	'sk' => 'Słowacja',
	'si' => 'Słowenia',
	'sh' => 'Święta Helena i Zależne',
	'tj' => 'Tadżykistan',
	'th' => 'Tajlandia',
	'tw' => 'Tajwan',
	'tz' => 'Tanzania',
	'tl' => 'Timor Wschodni',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trynidad i Tobago',
	'tn' => 'Tunezja',
	'tr' => 'Turcja',
	'tm' => 'Turkmenistan',
	'tv' => 'Tuvalu',
	'ug' => 'Uganda',
	'ua' => 'Ukraina',
	'uy' => 'Urugwaj',
	'uz' => 'Uzbekistan',
	'vu' => 'Vanuatu',
	'wf' => 'Wallis i Futuna',
	'va' => 'Watykan',
	've' => 'Wenezuela',
	'gb' => 'Wielka Brytania',
	'vn' => 'Wietnam',
	'ci' => 'Wybrzeże Kości Słoniowej',
	'bv' => 'Wyspa Bouveta',
	'cx' => 'Wyspa Bożego Narodzenia',
	'im' => 'Wyspa Man',
	'ax' => 'Wyspy Alandzkie',
	'ck' => 'Wyspy Cooka',
	'vi' => 'Wyspy Dziewicze Stanów Zjednoczonych',
	'hm' => 'Wyspy Heard i McDonalda',
	'cc' => 'Wyspy Kokosowe',
	'mh' => 'Wyspy Marshalla',
	'fo' => 'Wyspy Owcze',
	'sb' => 'Wyspy Salomona',
	'tc' => 'Wyspy Turks i Caicos',
	'st' => 'Wyspy Świętego Tomasza i Książęca',
	'hu' => 'Węgry',
	'it' => 'Włochy',
	'zm' => 'Zambia',
	'zw' => 'Zimbabwe',
	'ae' => 'Zjednoczone Emiraty Arabskie',
),

'miesiace' => array(
	'1' => 'Styczeń',
	'2' => 'Luty',
	'3' => 'Marzec',
	'4' => 'Kwiecień',
	'5' => 'Maj',
	'6' => 'Czerwiec',
	'7' => 'Lipiec',
	'8' => 'Sierpień',
	'9' => 'Wrzesień',
	'10' => 'Październik',
	'11' => 'Listopad',
	'12' => 'Grudzień',
),
);
