<?php


/**
 * Moduly dostepne w systemie.
 *
 * Po napisaniu nowego modulu nalezy dodac jego opis tutaj
 *
 * Dostepne typy modulow:
 * - 'zwykly',
 * - 'administracyjny',
 * - 'jednorazowy',
 * - 'blok'
 *
 */

return array(

/* MODUŁY ADMINISTRACYJNE */

array(
	'kod' => 'ModulyZarzadzanie',
	'nazwa' => 'Zarządzanie Modułami',
	'opis' => 'Odpowiada za zarzadzanie modułami w CMS-e',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//////'katalog_szablon' => 'ManagementModulesNew',
),

array(
	'kod' => 'KonfiguracjaSystemu',
	'nazwa' => 'Konfiguracja Systemu',
	'opis' => 'Odpowiada za zarzadzanie konfiguracją CMS-a i poszczególnych modułów',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'SystemConfigurationNew',
),

array(
	'kod' => 'UstawieniaJezykowe',
	'nazwa' => 'Ustawienia Językowe',
	'opis' => 'Odpowiada za zarzadzanie tłumaczeniami tresci CMS-a i poszczególnych modułów',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'LanguageSettingsNew',
),

array(
	'kod' => 'ProjektyZarzadzanie',
	'nazwa' => 'Zarządzanie Projektami',
	'opis' => 'Odpowiada za wszystkie operacjie zwiazane z zarządzaniem projektami',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'ProjectsMenagementNew',
),

array(
	'kod' => 'WidokiZarzadzanie',
	'nazwa' => 'Zarządzanie układmi stron',
	'opis' => 'Odpowiada za zarzadzanie układami stron w serwisie oraz zarządzanie ich treściami',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'ViewsManagementNew',
),

array(
	'kod' => 'KategorieZarzadzanie',
	'nazwa' => 'Zarządzanie Kategoriami',
	'opis' => 'Odpowiada za zarzadzanie kategoriami w serwisie',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'CategoriesManagementNew',
),

array(
	'kod' => 'UzytkownicyZarzadzanie',
	'nazwa' => 'Zarządzanie Użytkownikami',
	'opis' => 'Odpowiada za zarządzanie uzytkownikami ',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => '',
),

array(
	'kod' => 'UprawnieniaZarzadzanie',
	'nazwa' => 'Zarządzanie Uprawnieniami Użytkowników',
	'opis' => 'Odpowiada za zarządzanie uprawnieniami uzytkowników do poszczególnych kategorii i akcji',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'AuthorityManagementNew',
),

array(
	'kod' => 'CacheZarzadzanie',
	'nazwa' => 'Zarządzanie Cache-em systemu',
	'opis' => 'Odpowiada za zarządzanie różnymi rodzajami cache w CMS-e',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'CacheMenagementNew',
),

array(
	'kod' => 'ZadaniaCykliczne',
	'nazwa' => 'Zarządzanie zadaniami cyklicznymi',
	'opis' => 'Odpowiada za zarządzanie zadaniami cyklicznymi w systemie',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'CronNew',
),

array(
	'kod' => 'PlikiPrywatne',
	'nazwa' => 'Menedżer plików prywatnych',
	'opis' => 'Moduł do wyświetlania i zarządzania plikami z chronionym dostępem',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => '',
),

array(
	'kod' => 'PlikiPubliczne',
	'nazwa' => 'Menedżer plików',
	'opis' => 'Moduł do wyświetlania i zarządzania plikami z publicznym dostępem',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'PublicFilesNew',
),

array(
	'kod' => 'LogowanieOperacji',
	'nazwa' => 'Logowanie Operacji',
	'opis' => 'Odpowiada za logowanie działań użytkowników w systemie',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	////'katalog_szablon' => 'LogsNew',
),

array(
	'kod' => 'EmailZarzadzanie',
	'nazwa' => 'Zarzadzanie Wiadomościami Email',
	'opis' => 'Odpowiada za zarządzanie wiadomościami email w systemie',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'EmailMenagementNew',
),

array(
	'kod' => 'UserAccount',
	'nazwa' => 'Konto Administracyjne',
	'opis' => 'Odpowiada za poprawne zalogowanie uzytkownika do systemu, oraz zmiane ustawien uzytkownika',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'MenuAdministracyjne',
	'nazwa' => 'Menu Administracyjne',
	'opis' => '',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'AdminMenuNew',
),
	
array(
	'kod' => 'MenuAplikacji',
	'nazwa' => 'Menu Aplikacji',
	'opis' => 'Skróty do najczęstszych akcji, do pofiltrowanych wyników',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'ApplicationMenuNew',
),

array(
	'kod' => 'SciezkaAdministracyjna',
	'nazwa' => 'Scieżka Administracyjna',
	'opis' => 'Wyświetla ścieżkę do modulu, kategorii lub bloku którego tresc jest edytowna, zawiera tez pasek zmiany języka edycji.',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'BreadcrumbsNew',
),

array(
	'kod' => 'KategorieDrzewo',
	'nazwa' => 'Drzewo Kategorii',
	'opis' => 'Wyświela drzewko kategorii',
	'typ' => 'administracyjny',
	'wymagane' => array('KategorieZarzadzanie'),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'UserAccountBlock',
	'nazwa' => 'Blok zalogowanego użytkownika',
	'opis' => 'Wyświetla zalogowanego użytkownika i przycisk wyloguj',
	'typ' => 'administracyjny',
	'wymagane' => array('UserAccount'),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'UserAccountBlockNew',
),
	
array(
	'kod' => 'BlokKomunikator',
	'nazwa' => 'Blok komunikatora',
	'opis' => 'Blok do przechwytywania ztagowanych linków i wysyłania SMSów, maili',
	'typ' => 'administracyjny',
	'wymagane' => array('Sms'),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'MessengerBlockNew',
),

array(
	'kod' => 'KontoUzytkownika',
	'nazwa' => 'Konto Uzytkownika',
	'opis' => 'Odpowiada za poprawne zalogowanie uzytkownika do systemu, oraz zmiane ustawien uzytkownika',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'EdytorGraficzny',
	'nazwa' => 'Edytor grafiki',
	'opis' => 'Moduł do edycji plików graficznych',
	'typ' => 'administracyjny',
	'wymagane' => array('PlikiPubliczne'),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'Testy',
	'nazwa' => 'Testy serwisu',
	'opis' => 'Moduł do przeprowadzania różnego rodzaju testów w serwisie',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'TestsNew',
),

array(
	'kod' => 'Mailing',
	'nazwa' => 'Wysylka mailing\'ów',
	'opis' => 'Moduł do wysyłania mailing\'ów na podstawie list adresów',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'MailingNew',
),

array(
	'kod' => 'Routing',
	'nazwa' => 'Zarzadzanie regułami routingu.',
	'opis' => 'Moduł służący zarządzaniu regułami routingu oraz ich kolejnością.',
	'typ' => 'administracyjny',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'RoutingNew',
),

/* MODUŁY ZWYKŁE */

array(
	'kod' => 'WidokPoczatkowy',
	'nazwa' => 'Widok startowy',
	'opis' => 'Odpowiada za wyświetlenie widoku pocztkowego po zalogowaniu',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
    'kod' => 'Wyszukiwarka',
    'nazwa' => 'Wyszukiwarka',
    'opis' => 'Wyświetla wyniki wyszukiwania',
    'typ' => 'jednorazowy',
    'wymagane' => array(),
    'dla_zalogowanych' => false,
    'uslugi' => array('Admin', 'Http'),
    'cache' => false,
    'katalog_szablon' => '',
    //'katalog_szablon' => '',
),

array(
	'kod' => 'StronaOpisowa',
	'nazwa' => 'Strona Opisowa',
	'opis' => 'Strona z dowolną treścią, zdjęciami i dodatkowymi plikami',
	'typ' => 'zwykly',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
    'kod' => 'FormularzKontaktowy',
    'nazwa' => 'Formularz kontaktowy',
    'opis' => 'Formularz kontaktowy',
    'typ' => 'zwykly',
    'wymagane' => array(),
    'dla_zalogowanych' => false,
    'uslugi' => array('Admin','Http'),
    'cache' => true,
    'katalog_szablon' => '',
    //'katalog_szablon' => '',
),

array(
	'kod' => 'Aktualnosci',
	'nazwa' => 'Aktualności',
	'opis' => 'Moduł newsów na stronie',
	'typ' => 'zwykly',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http','Rss'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'Galeria',
	'nazwa' => 'Galerie Zdjęć',
	'opis' => 'Moduł do zarządzania galeriami i plikami znajdujacymi się w nich',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'MapaStrony',
	'nazwa' => 'Mapa Strony',
	'opis' => 'Wyświetla mapę strony',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'CropperZdjec',
	'nazwa' => 'Cropper Zdjec',
	'opis' => 'Moduł do ręcznego przycinania miniaturek zdjęć',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'RejestrowanieZdarzen',
	'nazwa' => 'Rejestrowanie zdarzeń',
	'opis' => 'Moduł rejestrujacy zdarzenia',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),


array(
	'kod' => 'Attachments',
	'nazwa' => 'Attachments',
	'opis' => 'Attachments',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),	
array(
	'kod' => 'Klienci',
	'nazwa' => 'Zarządzanie Klientami',
	'opis' => 'Odpowiada za zarządzanie listą klientów',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),
array(
	'kod' => 'Notes',
	'nazwa' => 'Zarządzanie notatkami',
	'opis' => 'Odpowiada za zarządzanie notatkami przypisanymi objektów',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),
/**
array(
	'kod' => 'Sms',
	'nazwa' => 'Sms',
	'opis' => 'Sms module',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Api'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),
 */

array(
	'kod' => 'Produkty',
	'nazwa' => 'Zarządzanie produktami',
	'opis' => 'Zarządznie produktami',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),
array(
	'kod' => 'Reports',
	'nazwa' => 'Reports',
	'opis' => 'Raporty',
	'typ' => 'jednorazowy',
	'wymagane' => array(),
	'dla_zalogowanych' => true,
	'uslugi' => array('Admin', 'Cron'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),


/* DODATKOWE BLOKI */

array(
	'kod' => 'BlokOpisowy',
	'nazwa' => 'Blok Opisowy',
	'opis' => 'Blok z dowolną treścią, zdjęciami i dodatkowymi plikami',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokMenu',
	'nazwa' => 'Blok Menu',
	'opis' => 'Blok generujacy pełne menu z wybranych pozycji',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokSciezka',
	'nazwa' => 'Blok ścieżka',
	'opis' => 'Blok generujący ścieżkę do kategorii',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokAktualnosci',
	'nazwa' => 'Blok aktualności',
	'opis' => 'Blok odpowiedzialny za wyświetlanie skrótów aktualności/ogłoszeń',
	'typ' => 'blok',
	'wymagane' => array('Aktualnosci'),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),


array(
	'kod' => 'BlokKontoUzytkownika',
	'nazwa' => 'Blok konto użytkownika',
	'opis' => 'Odpowiada za zalogowanie uzytkownika do systemu',
	'typ' => 'blok',
	'wymagane' => array('KontoUzytkownika'),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokMenuCzesciowe',
	'nazwa' => 'Blok Menu Częściowe',
	'opis' => 'Blok generujacy menu od dowolnej kategorii',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokJezyki',
	'nazwa' => 'Blok zmiany języka',
	'opis' => 'Blok generujacy linki do zmiany języka strony',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => false,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokCzytnikRss',
	'nazwa' => 'Blok czytnika Rss',
	'opis' => 'Blok agregujący kanały rss i wyświetlający listę wpisów',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => '',
),

array(
	'kod' => 'BlokObecnoscUzytkownika',
	'nazwa' => 'Blok obecność użytkownika',
	'opis' => 'Blok monitorujący fakt zalogowania użytkownika.',
	'typ' => 'blok',
	'wymagane' => array(),
	'dla_zalogowanych' => false,
	'uslugi' => array('Admin','Http'),
	'cache' => true,
	'katalog_szablon' => '',
	//'katalog_szablon' => 'UserPresenceBlock',
),
array(
    'kod' => 'BlokWyszukiwarki',
    'nazwa' => 'Blok z wyszukiwarka',
    'opis' => 'Blok z formularzem wyszukiwarki',
    'typ' => 'blok',
    'wymagane' => array(),
    'dla_zalogowanych' => false,
    'uslugi' => array('Admin','Http'),
    'cache' => true,
    'katalog_szablon' => '',
    //'katalog_szablon' => 'UserPresenceBlock',
),


);
