<?php
return array (
	'Generic\ModelNosql\LogZdarzen' => array(
        'fields' => array(
            'timestamp' => 'date',
            'idPracownika' => 'integer',
            'idObiektuGlownego' => 'integer',
            'typObiektuGlownego' => 'string',
            'danePomocnicze' => 'serialized',
            'nazwa' => 'string',
            'tokenProcesu' => 'string',
        ),
    ),
	'Generic\ModelNosql\LogProcesow' => array(
        'fields' => array(
            'start' => 'date',
            'stop' => 'date',
            'idPracownika' => 'integer',
            'idObiektuGlownego' => 'integer',
            'typObiektuGlownego' => 'string',
            'danePomocnicze' => 'serialized',
            'nazwaProcesu' => 'string',
        ),
    ),
	'Generic\ModelNosql\UzytkownikWersja' => array(
        'fields' => array(
			'dataWersji' => 'date',
			'idTworzacegoWersje' => 'integer',
			'idObiektu' => 'integer',
			'idProjektu' => 'integer',
			'login' => 'string',
			'haslo' => 'string',
			'email' => 'string',
			'dataDodania' => 'date',
			'dataAktywacji' => 'date',
			'token' => 'string',
			'czyAdmin' => 'boolean',
			'status' => 'string',
			'imie' => 'string',
			'nazwisko' => 'string',
			'dataUrodzenia' => 'date',
			'plec' => 'string',
			'kontaktTelefon' => 'string',
			'kontaktKomorka' => 'string',
			'kontaktFax' => 'string',
			'kontaktWWW' => 'string',
			'kontaktNazwa' => 'string',
			'kontaktAdres' => 'string',
			'kontaktKodPocztowy' => 'string',
			'kontaktMiasto' => 'string',
			'firmaNazwa' => 'string',
			'firmaNip' => 'string',
			'firmaAdres' => 'string',
			'firmaKodPocztowy' => 'string',
			'firmaMiasto' => 'string',
			'pocztaHost' => 'string',
			'pocztaPort' => 'integer',
			'pocztaLogin' => 'string',
			'pocztaHaslo' => 'string',
			'jezyk' => 'string',
			'zgodaMailing' => 'integer',
			'zgodaMarketing' => 'integer',
			'typAktywacji' => 'string',
			'numerKontaBankowego' => 'string',
			'numerUmowy' => 'string',
			'mapaSzerokosc' => 'string',
			'mapaDlugosc' => 'string',
        ),
    ),
);
